repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
  # - repo: local
  #   hooks:
  #     - id: flake8
  #       name: "Flake8: Style guide checking"
  #       entry: poetry run flake8
  #       exclude: ^tests|migrations/
  #       files: \.py$
  #       language: system
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.902
  #   hooks:
  #     - id: mypy
  #       exclude: ^tests/
  #       additional_dependencies:
  #         - types-requests
  #         - types-cryptography
  # - repo: local
  #   hooks:
  #     - id: mypy
  #       name: "MyPy: Type checking"
  #       entry: poetry run mypy
  #       files: \.py$
  #       language: system
  # - repo: https://github.com/jendrikseipp/vulture
  #   rev: "v2.3"
  #   hooks:
  #     - id: vulture
