name: TODOs extraction

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Search for TODOs
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "TODOs to Issues"
        uses: "alstr/todo-to-issue-action@v4.5"
        id: "todo"
